using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace wfaRcptPrg {
   internal sealed class AllIngrES {
      public static string strIngredients =
        "aceite\n" +
        "aceituna\n" +
        "aceitunas\n" +
        "acelga\n" +
        "acelgas\n" +
        "achicoria\n" +
        "aderezo\n" +
        "aguacates\n" +
        "ajete\n" +
        "ajos\n" +
        "albahaca\n" +
        "albaricoque\n" +
        "albariño\n" +
        "alcachofa\n" +
        "alcachofas\n" +
        "alcaparra\n" +
        "alcaparras\n" +
        "alioli\n" +
        "almeja\n" +
        "almejas\n" +
        "almendra\n" +
        "almendras\n" +
        "alubia\n" +
        "alubias\n" +
        "anchoa\n" +
        "anchoas\n" +
        "anguila\n" +
        "anguilas\n" +
        "anises\n" +
        "anís\n" +
        "apio\n" +
        "apios\n" +
        "arroz\n" +
        "atunes\n" +
        "atún\n" +
        "avellanas\n" +
        "azafrán\n" +
        "azucarillo\n" +
        "azúcar\n" +
        "bacalada\n" +
        "bacalao\n" +
        "bacon\n" +
        "becadas\n" +
        "bechamel\n" +
        "beicon\n" +
        "bendito\n" +
        "berenjenas\n" +
        "berros\n" +
        "berza\n" +
        "berza campía\n" +
        "berza silvestre\n" +
        "besugo\n" +
        "besugos\n" +
        "bizcochito\n" +
        "bizcochitos\n" +
        "bizcocho\n" +
        "bizcochos\n" +
        "bonito\n" +
        "bonitos\n" +
        "boquerones\n" +
        "borrajas\n" +
        "brandy\n" +
        "brécol\n" +
        "caballa\n" +
        "caballas\n" +
        "cabello\n" +
        "cabellos\n" +
        "cabeza de ajo\n" +
        "cacahuetes\n" +
        "cacao\n" +
        "café\n" +
        "calabacines\n" +
        "calabacín\n" +
        "calabaza\n" +
        "calabazas\n" +
        "calamar\n" +
        "calamares\n" +
        "caldo\n" +
        "callos\n" +
        "canela\n" +
        "canelone\n" +
        "canelones\n" +
        "carabinero\n" +
        "caramelo\n" +
        "caramelos\n" +
        "cardo\n" +
        "carioca\n" +
        "carpa\n" +
        "castaña\n" +
        "cava\n" +
        "cayena\n" +
        "cazón\n" +
        "aros de cebolla\n" +
        "cebolla\n" +
        "cebolleta\n" +
        "centollo\n" +
        "cerdo\n" +
        "cerefolio\n" +
        "cereza\n" +
        "cerezas\n" +
        "cerveza\n" +
        "chalota\n" +
        "champiñon\n" +
        "champiñones\n" +
        "changurro\n" +
        "cherevía\n" +
        "cherna\n" +
        "chernas\n" +
        "chicharro\n" +
        "chirimoya\n" +
        "chirivia\n" +
        "chirivía\n" +
        "chistorra\n" +
        "chocolate\n" +
        "chorizo\n" +
        "ciruela\n" +
        "clara\n" +
        "claras\n" +
        "clavo\n" +
        "coco\n" +
        "codillo\n" +
        "codito\n" +
        "codornice\n" +
        "cogollo\n" +
        "cogote\n" +
        "coliflor\n" +
        "colinabo\n" +
        "colza\n" +
        "comino\n" +
        "conejo\n" +
        "coñac\n" +
        "confitada\n" +
        "congrio\n" +
        "cordero\n" +
        "crepes\n" +
        "cuajada\n" +
        "cuajo\n" +
        "cuello\n" +
        "curry\n" +
        "dátile\n" +
        "demi-glace\n" +
        "elafobosco\n" +
        "emmental\n" +
        "empana\n" +
        "endibia\n" +
        "eneldo\n" +
        "escarola\n" +
        "espaguetis\n" +
        "espinaca\n" +
        "espárrago\n" +
        "estragón\n" +
        "faneca\n" +
        "fideo\n" +
        "foie\n" +
        "foie-gras\n" +
        "frambuesa\n" +
        "fresa\n" +
        "fresas\n" +
        "fresone\n" +
        "fruta\n" +
        "fruto\n" +
        "fumet\n" +
        "fécula\n" +
        "gajo\n" +
        "galleta\n" +
        "gallinas\n" +
        "gallineta\n" +
        "gallos\n" +
        "gambas\n" +
        "garbanzos\n" +
        "gelatina\n" +
        "glace\n" +
        "glacé\n" +
        "granadina\n" +
        "grand marnier\n" +
        "grelos\n" +
        "grosella\n" +
        "guinda\n" +
        "guindilla\n" +
        "guindillitas\n" +
        "guisante\n" +
        "haba\n" +
        "habas\n" +
        "harina\n" +
        "helado\n" +
        "hielo\n" +
        "hierba\n" +
        "hierbabuena\n" +
        "higadillos\n" +
        "higo\n" +
        "hinojo\n" +
        "hojaldre\n" +
        "huevos\n" +
        "hígado\n" +
        "ijadas\n" +
        "jabalí\n" +
        "jalea\n" +
        "jamón\n" +
        "jarabe\n" +
        "jerez\n" +
        "jerez seco\n" +
        "judías\n" +
        "jurele\n" +
        "kiwi\n" +
        "langostino\n" +
        "lasaña\n" +
        "laurel\n" +
        "leche\n" +
        "lechuga\n" +
        "legumbre\n" +
        "lengua\n" +
        "lenguado\n" +
        "lenteja\n" +
        "levadura\n" +
        "licor\n" +
        "liebre\n" +
        "limonero\n" +
        "limones\n" +
        "limón\n" +
        "limóna\n" +
        "lubina\n" +
        "lubinas\n" +
        "macarrone\n" +
        "macarrones\n" +
        "mahonesa\n" +
        "maicena\n" +
        "maizena\n" +
        "mandarina\n" +
        "mandarinas\n" +
        "mango\n" +
        "mangos\n" +
        "manteca\n" +
        "mantequilla\n" +
        "manzana\n" +
        "manzanas\n" +
        "margarina\n" +
        "maíz\n" +
        "mejillone\n" +
        "mejillones\n" +
        "melocotones\n" +
        "melocotón\n" +
        "melon\n" +
        "melones\n" +
        "melón\n" +
        "membrillo\n" +
        "membrillos\n" +
        "menta\n" +
        "merluza\n" +
        "merluzas\n" +
        "mermelada\n" +
        "mero\n" +
        "meros\n" +
        "mojarras\n" +
        "molleja\n" +
        "mollejas\n" +
        "morcilla\n" +
        "morcillas\n" +
        "moscada\n" +
        "moscadas\n" +
        "mostaza\n" +
        "mozzarella\n" +
        "naba\n" +
        "nabicol\n" +
        "nabilla\n" +
        "nabina\n" +
        "nabo\n" +
        "nabo gallego\n" +
        "nabo largo\n" +
        "nabo redondo\n" +
        "nabos\n" +
        "naranja\n" +
        "naranjas\n" +
        "nata\n" +
        "natillas\n" +
        "nuece\n" +
        "nuez\n" +
        "níspero\n" +
        "nísperos\n" +
        "obleas\n" +
        "oporto\n" +
        "ortigas\n" +
        "orégano\n" +
        "paloma\n" +
        "palomas\n" +
        "pan\n" +
        "panceta\n" +
        "parmesano\n" +
        "pasas\n" +
        "pasaso\n" +
        "pasta\n" +
        "pastas\n" +
        "pastelera\n" +
        "pastinaca\n" +
        "pastinacas\n" +
        "patata\n" +
        "patatas\n" +
        "pato\n" +
        "patos\n" +
        "paté\n" +
        "pavo\n" +
        "pavos\n" +
        "penca\n" +
        "pencas\n" +
        "pepinillo\n" +
        "pepinillos\n" +
        "pepino\n" +
        "pepinos\n" +
        "pera\n" +
        "peras\n" +
        "perdice\n" +
        "perdices\n" +
        "perdiz\n" +
        "perejil\n" +
        "perifolio\n" +
        "perifollo\n" +
        "perifollos\n" +
        "perlones\n" +
        "perlón\n" +
        "pernil\n" +
        "perrins\n" +
        "pescadilla\n" +
        "pescadillas\n" +
        "pilchard\n" +
        "pilchards\n" +
        "pimentón\n" +
        "pimienta\n" +
        "pimiento\n" +
        "pimientos\n" +
        "pintaroja\n" +
        "pintarojas\n" +
        "pistacho\n" +
        "pistachos\n" +
        "pizza\n" +
        "piña\n" +
        "piñon\n" +
        "piñones\n" +
        "plátano\n" +
        "plátanos\n" +
        "pochas\n" +
        "pollito\n" +
        "pollitos\n" +
        "pollo\n" +
        "pollos\n" +
        "pomelo\n" +
        "puerro\n" +
        "puerros\n" +
        "pulpo\n" +
        "pulpos\n" +
        "quesito\n" +
        "quesitos\n" +
        "queso\n" +
        "quinoa\n" +
        "raba\n" +
        "rabanito\n" +
        "rape\n" +
        "rapes\n" +
        "ravioli\n" +
        "raya\n" +
        "rayas\n" +
        "remolacha\n" +
        "remolachas\n" +
        "requesón\n" +
        "ribeiro\n" +
        "ricota\n" +
        "rodaballo\n" +
        "rodaballos\n" +
        "romero\n" +
        "romerón\n" +
        "romiru\n" +
        "ron\n" +
        "rosmarino\n" +
        "rumaní\n" +
        "sal\n " +
        "salami\n" +
        "salchicha\n" +
        "salchichas\n" +
        "salchichón\n" +
        "salmones\n" +
        "salmonete\n" +
        "salmonetes\n" +
        "salmón\n" +
        "sandía\n" +
        "sardin\n" +
        "sardinas\n" +
        "sargo\n" +
        "sargos\n" +
        "semiglaseado\n" +
        "sesos\n" +
        "seta\n" +
        "setas\n" +
        "sidra\n" +
        "sobrasada\n" +
        "soja\n" +
        "soletilla\n" +
        "solomillo\n" +
        "solomillos\n" +
        "tabasco\n" +
        "taca\n" +
        "tallarine\n" +
        "tallarines\n" +
        "tapioca\n" +
        "ternera\n" +
        "tinta\n" +
        "tocineta\n" +
        "tocino\n" +
        "tolla\n" +
        "tomate\n" +
        "tomillo\n" +
        "tomillos\n" +
        "tortellini\n" +
        "treviso\n" +
        "trucha\n" +
        "truchas\n" +
        "trufa\n" +
        "trufas\n" +
        "turrón\n" +
        "turrónes\n" +
        "txacoli\n" +
        "txakoli\n" +
        "txakolí\n" +
        "txakolío\n" +
        "txangurro\n" +
        "uva\n" +
        "uvas\n" +
        "vaca\n" +
        "vacuno\n" +
        "vacunos\n" +
        "vaina\n" +
        "vainas\n" +
        "vainilla\n" +
        "ventresca\n" +
        "verdel\n" +
        "verdele\n" +
        "verdeles\n" +
        "verdura\n" +
        "verduras\n" +
        "vinagre\n" +
        "vino\n" +
        "vinos\n" +
        "vodka\n" +
        "vodkas\n" +
        "volovane\n" +
        "volovanes\n" +
        "yogur\n" +
        "zanahoria\n" +
        "zanahoria blanco\n" +
        "zanahorias\n" +
        "zancarró";
   }
}