//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfaRcptPrg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wfaRcptPrg.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Recetas.
        /// </summary>
        internal static string Form1_AddStatusBar__Recetas {
            get {
                return ResourceManager.GetString("Form1_AddStatusBar__Recetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo encontré:.
        /// </summary>
        internal static string Form1_AddStatusBar_Lo_encontré_ {
            get {
                return ResourceManager.GetString("Form1_AddStatusBar_Lo_encontré_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de receta: .
        /// </summary>
        internal static string Form1_AddStatusBar_Número_de_receta__ {
            get {
                return ResourceManager.GetString("Form1_AddStatusBar_Número_de_receta__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Recetas.
        /// </summary>
        internal static string Form1_DisplayRecipe__Recetas {
            get {
                return ResourceManager.GetString("Form1_DisplayRecipe__Recetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontré:.
        /// </summary>
        internal static string Form1_DisplayRecipe_Encontré_ {
            get {
                return ResourceManager.GetString("Form1_DisplayRecipe_Encontré_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeración  del receta: .
        /// </summary>
        internal static string Form1_DisplayRecipe_numeración__del_receta__ {
            get {
                return ResourceManager.GetString("Form1_DisplayRecipe_numeración__del_receta__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota: Haz clic con el ratón en el cuadro de lista con los nombres de las recetas o usa la búsqueda de ingrediente y receta.....
        /// </summary>
        internal static string Form1_lbxRecipeNames_SelectedIndexChanged_Nota__Haz_clic_con_el_ratón_en_el_cuadro_de_lista_con_los_nombres_de_las_recetas_o_usa_la_búsqueda_de_ingrediente_y_receta____ {
            get {
                return ResourceManager.GetString("Form1_lbxRecipeNames_SelectedIndexChanged_Nota__Haz_clic_con_el_ratón_en_el_cuadr" +
                        "o_de_lista_con_los_nombres_de_las_recetas_o_usa_la_búsqueda_de_ingrediente_y_rec" +
                        "eta____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nombre nuevo receta: .
        /// </summary>
        internal static string Form1_mnuNew_Click__Nombre_nuevo_receta__ {
            get {
                return ResourceManager.GetString("Form1_mnuNew_Click__Nombre_nuevo_receta__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre ya exist.
        /// </summary>
        internal static string Form1_mnuNew_Click_Nombre_ya_exist {
            get {
                return ResourceManager.GetString("Form1_mnuNew_Click_Nombre_ya_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo nombre: .
        /// </summary>
        internal static string Form1_mnuNew_Click_Nuevo_nombre__ {
            get {
                return ResourceManager.GetString("Form1_mnuNew_Click_Nuevo_nombre__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡La receta está guardada!.
        /// </summary>
        internal static string Form1_mnuSaveAs_Click_ {
            get {
                return ResourceManager.GetString("Form1_mnuSaveAs_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de receta seleccionado se elimina.
        /// </summary>
        internal static string Form1_RemoveSelectedRecpe_El_nombre_de_receta_seleccionado_se_elimina {
            get {
                return ResourceManager.GetString("Form1_RemoveSelectedRecpe_El_nombre_de_receta_seleccionado_se_elimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Haga clic en - Archivo|Guardar - cuando termine!.
        /// </summary>
        internal static string Form1_rtbxValues_TextChanged_ {
            get {
                return ResourceManager.GetString("Form1_rtbxValues_TextChanged_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya hay 9 recetas almacenadas. La receta se almacena con el nombre: 
        ///
        ///.
        /// </summary>
        internal static string Form1_SaveEditedRecipe_ {
            get {
                return ResourceManager.GetString("Form1_SaveEditedRecipe_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receta guardada con nuevo nombre: .
        /// </summary>
        internal static string Form1_SaveEditedRecipe_Receta_guardada_con_nuevo_nombre__ {
            get {
                return ResourceManager.GetString("Form1_SaveEditedRecipe_Receta_guardada_con_nuevo_nombre__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No encontrado!.
        /// </summary>
        internal static string Form1_SaveWithSelectedRcptName_ {
            get {
                return ResourceManager.GetString("Form1_SaveWithSelectedRcptName_", resourceCulture);
            }
        }
    }
}
